[package]
name = "word_displayer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
egui = "0.31"
rayon = "1"
walkdir = "2"

[target.'cfg(windows)'.dependencies]
# 只为了注册 Ctrl+9 这个全局热键
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
